// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportClub.API.Data;

#nullable disable

namespace SportClub.API.Migrations
{
    [DbContext(typeof(SportClubDbContext))]
    partial class SportClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportClub.API.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instructor = "Marcel",
                            LocationId = 2,
                            StartDateTime = new DateTime(2023, 2, 14, 19, 30, 0, 0, DateTimeKind.Local),
                            WorkOutId = 1
                        },
                        new
                        {
                            Id = 2,
                            Instructor = "Coen",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 20, 18, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 2
                        },
                        new
                        {
                            Id = 3,
                            Instructor = "Freek",
                            LocationId = 1,
                            StartDateTime = new DateTime(2023, 2, 14, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 3
                        },
                        new
                        {
                            Id = 4,
                            Instructor = "Miriam",
                            LocationId = 5,
                            StartDateTime = new DateTime(2023, 2, 20, 20, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 5
                        },
                        new
                        {
                            Id = 5,
                            Instructor = "Marcel",
                            LocationId = 7,
                            StartDateTime = new DateTime(2023, 2, 18, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 6
                        },
                        new
                        {
                            Id = 6,
                            Instructor = "Laura",
                            LocationId = 9,
                            StartDateTime = new DateTime(2023, 2, 17, 19, 30, 0, 0, DateTimeKind.Local),
                            WorkOutId = 9
                        },
                        new
                        {
                            Id = 7,
                            Instructor = "Emilio",
                            LocationId = 6,
                            StartDateTime = new DateTime(2023, 2, 19, 11, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 7
                        },
                        new
                        {
                            Id = 8,
                            Instructor = "Judith",
                            LocationId = 8,
                            StartDateTime = new DateTime(2023, 2, 14, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 8
                        },
                        new
                        {
                            Id = 9,
                            Instructor = "Eva",
                            LocationId = 9,
                            StartDateTime = new DateTime(2023, 2, 14, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 9
                        },
                        new
                        {
                            Id = 10,
                            Instructor = "Suzanne",
                            LocationId = 10,
                            StartDateTime = new DateTime(2023, 2, 14, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 10
                        },
                        new
                        {
                            Id = 11,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 20, 17, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 12,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 14, 17, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 13,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 15, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 14,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 16, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 15,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 17, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 16,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 18, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 17,
                            Instructor = "",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 19, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 4
                        });
                });

            modelBuilder.Entity("SportClub.API.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsOutside")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Brouwmeesterstraat 10 Breda",
                            Capacity = 25,
                            IsOutside = false,
                            Name = "ApenkooiGym"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Spinveld 66 A1 Breda",
                            Capacity = 60,
                            IsOutside = false,
                            Name = "Boulderhal Bruut"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Wilderen 2, 4817 VG Breda",
                            Capacity = 20,
                            IsOutside = true,
                            Name = "Wilderen 2 Breda"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 30,
                            IsOutside = true,
                            Name = "BRESS Sportcentrum, Dance Studio 1"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 20,
                            IsOutside = true,
                            Name = "BRESS Sportcentrum, Dance Studio 2"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Pastoor Pottersplein 12, 4815 BC Breda",
                            Capacity = 25,
                            IsOutside = true,
                            Name = "Belcrumhuis"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 25,
                            IsOutside = false,
                            Name = "BRESS Sportcentrum, Fitness"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Terheijdenseweg 508 Breda",
                            Capacity = 16,
                            IsOutside = true,
                            Name = "TVBN Tennisvereniging Breda Noord"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Dr. Schaepmanlaan 4 Breda",
                            Capacity = 16,
                            IsOutside = false,
                            Name = "Atletiekvereniging SPRINT"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Teteringsedijk 145, 4817 MD Breda",
                            Capacity = 12,
                            IsOutside = false,
                            Name = "Ortega Diving"
                        });
                });

            modelBuilder.Entity("SportClub.API.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "conditie en kracht",
                            Description = "Bootcamp is groepstraining die conditie- en krachtoefeningen combineert en buiten plaatsvindt. Tijdens veel oefeningen wordt er gebruik gemaakt van eigen lichaamsgewicht en obstakels die in de omgeving aanwezig zijn, denk bijvoorbeeld aan bankjes, stoepranden en hekken. Sommige oefeningen doe je in tweetallen of in kleine groepjes, zodat je elkaar kunt gebruiken om bepaalde oefeningen uit te voeren en elkaar aan te moedigen. Samen bereik je meer!",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-23-om-16.47.36-1024x959.png",
                            Price = 2.5m,
                            Title = "Bootcamp"
                        },
                        new
                        {
                            Id = 4,
                            Category = "conditie en kracht",
                            Description = "Boulderen is een spectaculaire vorm van klimmen en komt voort uit het beklimmen van rotsblokken. Anders dan bij klimmen heb je bij boulderen geen touw en klimgordels nodig. Dikke valmatten onder de routes zorgen voor veiligheid. De klimwanden in de boulderhal hebben een maximale hoogte van 4,5 meter en variëren van voorover neigend tot en met fors achterover hellend. Het is een sport voor vrijwel iedereen en kan zowel individueel als in groepsverband beoefend worden. Door de mix van de verschillende wanden en boulders kunnen zowel beginnende klimmers als gevorderden naast en met elkaar boulderen.",
                            Duration = 120,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/bouldering-2021-08-28-18-47-52-utc-scaled-e1650881591375-1024x530.jpg",
                            Price = 6.5m,
                            Title = "Boulderen"
                        },
                        new
                        {
                            Id = 2,
                            Category = "kracht",
                            Description = "Tijdens de high intensity training BoxFit krijg je te maken met een combinatie van bokstechnieken en oefeningen met eigen lichaamsgewicht, waarbij fun en samenwerking centraal staat.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-17.27.25-1022x1024.png",
                            Title = "BoxFit"
                        },
                        new
                        {
                            Id = 3,
                            Category = "conditie en kracht",
                            Description = "Bij onze gymlessen maak je na een lange werkdag je hoofd weer even helemaal leeg. De nostalgie slaat zó hard in dat de smaak van Wicky spontaan weer te proeven is! Elke les bestaat uit een warming-up, een hoofdspel en een eindspel. De opgeleide meesters en juffen van ApenkooiGym doen er alles aan om jou zo hard mogelijk door de zaal te laten gieren. De ene keer is dat met Apenkooien, de andere keer met bestaande of zelfbedachte spellen als James Bond, het Grote Waterspektakel, Super Mario Kart of één van de vele varianten op trefbal. Al deze spellen zijn (her)uitgevonden voor volwassenen. Nooit kinderachtig, altijd met kinderlijk plezier. Door het trainen van je lachspieren heb je bijna niet in de gaten dat je met een aardige work-out bezig bent.",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-14.52.29-1024x854.png",
                            Price = 2.5m,
                            Title = "Gymmen"
                        },
                        new
                        {
                            Id = 5,
                            Category = "cardio",
                            Description = "Spinning is een high intensity groepsles waarbij je op een leuke manier je conditie in hoog tempo verbetert. Je doet dit op een vaststaande fiets, met extra weerstand. Hoeveel weerstand? Dit bepaal je helemaal zelf! Hierdoor is deze les geschikt voor iedereen. De instructeur geeft instructies terwijl de muziek het tempo ondersteunt.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-14.40.03-1024x939.png",
                            Title = "Spinning"
                        },
                        new
                        {
                            Id = 7,
                            Category = "kracht",
                            Description = "Onze fitness beschikt over de up-to-date cardio- en krachtapparatuur van Matrix Fitness en daarnaast ook over een free weight area waar je alle ruimte hebt om (grond)oefeningen te doen of te trainen met dumbbells, barbells en andere materialen.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/interior-of-fitness-hall-with-fitness-bicycles-2021-08-28-00-35-59-utc-1024x683.jpg",
                            Title = "Fitness"
                        },
                        new
                        {
                            Id = 8,
                            Category = "balsport",
                            Description = "Tennis is een balsport voor twee spelers (enkelspel) of paren (dubbelspel). De tennisbal moet met een racket over een net op de speelhelft van de tegenspeler(s) geslagen worden. Het doel is om het de tegenspelers(s) onmogelijk te maken de bal terug te slaan.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/tennis-racket-and-tennis-net-on-tennis-court-2021-09-03-12-45-52-utc-1024x683.jpg",
                            Title = "Tennis"
                        },
                        new
                        {
                            Id = 9,
                            Category = "groepsles",
                            Description = "Aerial Silk is een unieke sport die zijn oorsprong kent in het circus. Tijdens het beoefenen van deze sport train je heel je lichaam en ontwikkel je evenwicht, kracht en flexibiliteit. Daarnaast krijg je echt een kick als je in de doeken hangt.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/adult-woman-practices-anti-gravity-yoga-position-i-2022-02-02-03-49-35-utc-1024x683.jpg",
                            Title = "Aerial Silk"
                        },
                        new
                        {
                            Id = 10,
                            Category = "groepsles",
                            Description = "Duiken is één van de snelst groeiende avontuurlijke sporten ter wereld en dat is niet zonder reden. Het ontspannen gevoel en het gevoel van gewichtloosheid (een gevoel dat verder alleen astronauten kunnen meemaken) maakt duiken tot een unieke sport. Duiken doe je altijd met minimaal 2 personen waardoor het ook nog eens een sociale sport is. Wist je trouwens dat het aardoppervlakte\r\nuit 70% water bestaat en dat er onder water meer verschillende soorten planten en dieren leven dan erboven? Er valt dus nog genoeg te ontdekken in de onderwaterwereld!",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-18-om-11.08.38-1024x327.png",
                            Title = "Duiken"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
