// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportClub.API.Data;

#nullable disable

namespace SportClub.API.Migrations
{
    [DbContext(typeof(SportClubDbContext))]
    partial class SportClubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportClub.API.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("lessons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instructor = "Marcel",
                            LocationId = 3,
                            StartDateTime = new DateTime(2023, 2, 28, 19, 30, 0, 0, DateTimeKind.Local),
                            WorkOutId = 12
                        },
                        new
                        {
                            Id = 2,
                            Instructor = "Coen",
                            LocationId = 5,
                            StartDateTime = new DateTime(2023, 2, 27, 18, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 15
                        },
                        new
                        {
                            Id = 3,
                            Instructor = "Freek",
                            LocationId = 2,
                            StartDateTime = new DateTime(2023, 2, 24, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 16
                        },
                        new
                        {
                            Id = 4,
                            Instructor = "Miriam",
                            LocationId = 6,
                            StartDateTime = new DateTime(2023, 2, 27, 20, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 17
                        },
                        new
                        {
                            Id = 5,
                            Instructor = "Marcel",
                            LocationId = 8,
                            StartDateTime = new DateTime(2023, 2, 25, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 1
                        },
                        new
                        {
                            Id = 6,
                            Instructor = "Laura",
                            LocationId = 10,
                            StartDateTime = new DateTime(2023, 2, 24, 19, 30, 0, 0, DateTimeKind.Local),
                            WorkOutId = 2
                        },
                        new
                        {
                            Id = 7,
                            Instructor = "Emilio",
                            LocationId = 7,
                            StartDateTime = new DateTime(2023, 2, 26, 11, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 18
                        },
                        new
                        {
                            Id = 8,
                            Instructor = "Judith",
                            LocationId = 9,
                            StartDateTime = new DateTime(2023, 2, 24, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 19
                        },
                        new
                        {
                            Id = 9,
                            Instructor = "Eva",
                            LocationId = 10,
                            StartDateTime = new DateTime(2023, 2, 24, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 2
                        },
                        new
                        {
                            Id = 10,
                            Instructor = "Suzanne",
                            LocationId = 11,
                            StartDateTime = new DateTime(2023, 2, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 20
                        },
                        new
                        {
                            Id = 11,
                            Instructor = "zelf trainen",
                            LocationId = 1,
                            StartDateTime = new DateTime(2023, 2, 24, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 4
                        },
                        new
                        {
                            Id = 12,
                            Instructor = "Robert",
                            LocationId = 5,
                            StartDateTime = new DateTime(2023, 2, 24, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            WorkOutId = 9
                        },
                        new
                        {
                            Id = 13,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 27, 17, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 14,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 28, 17, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 15,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 3, 1, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 16,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 3, 2, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 17,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 24, 14, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 18,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 25, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        },
                        new
                        {
                            Id = 19,
                            Instructor = "",
                            LocationId = 4,
                            StartDateTime = new DateTime(2023, 2, 26, 10, 0, 0, 0, DateTimeKind.Local),
                            WorkOutId = 14
                        });
                });

            modelBuilder.Entity("SportClub.API.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsOutside")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Nieuwe Inslag 99",
                            Capacity = 150,
                            IsOutside = false,
                            Name = "BRESS Sportcentrum"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Brouwmeesterstraat 10 Breda",
                            Capacity = 25,
                            IsOutside = false,
                            Name = "ApenkooiGym"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Spinveld 66 A1 Breda",
                            Capacity = 60,
                            IsOutside = false,
                            Name = "Boulderhal Bruut"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Wilderen 2, 4817 VG Breda",
                            Capacity = 20,
                            IsOutside = true,
                            Name = "Wilderen 2 Breda"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 30,
                            IsOutside = true,
                            Name = "BRESS Sportcentrum, Dance Studio 1"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 20,
                            IsOutside = true,
                            Name = "BRESS Sportcentrum, Dance Studio 2"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Pastoor Pottersplein 12, 4815 BC Breda",
                            Capacity = 25,
                            IsOutside = true,
                            Name = "Belcrumhuis"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Nieuwe Inslag 99, 4817 GN Breda",
                            Capacity = 25,
                            IsOutside = false,
                            Name = "BRESS Sportcentrum, Fitness"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Terheijdenseweg 508 Breda",
                            Capacity = 16,
                            IsOutside = true,
                            Name = "TVBN Tennisvereniging Breda Noord"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Dr. Schaepmanlaan 4 Breda",
                            Capacity = 16,
                            IsOutside = false,
                            Name = "Atletiekvereniging SPRINT"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Teteringsedijk 145, 4817 MD Breda",
                            Capacity = 12,
                            IsOutside = false,
                            Name = "Ortega Diving"
                        });
                });

            modelBuilder.Entity("SportClub.API.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("workouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "groepsles",
                            Description = "Combineer yoga, Thaise massage en acrobatiek met elkaar en je hebt AcroYoga.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/couple-in-park-practising-pair-acro-yoga-2022-02-02-05-06-46-utc-scaled-e1653915380837-1024x407.jpg",
                            Title = "Acro Yoga"
                        },
                        new
                        {
                            Id = 2,
                            Category = "groepsles",
                            Description = "Aerial Silk is een unieke sport die zijn oorsprong kent in het circus. Tijdens het beoefenen van deze sport train je heel je lichaam en ontwikkel je evenwicht, kracht en flexibiliteit. Daarnaast krijg je echt een kick als je in de doeken hangt.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/adult-woman-practices-anti-gravity-yoga-position-i-2022-02-02-03-49-35-utc-1024x683.jpg",
                            Title = "Aerial Silk"
                        },
                        new
                        {
                            Id = 3,
                            Category = "buiten sporten",
                            Description = "Atletiek is samen met de zwemsport de oudste sport ter wereld en wordt ook wel ‘de moeder der sporten’ genoemd omdat het de menselijke basisbewegingen (lopen, springen en werpen) omvat. Bij atletiek moeten sporters (de atleten) op individueel of in groepen (estafette) presteren en kan zowel op de weg als op de atletiekbaan worden beoefend.",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-30-om-14.36.33-1024x329.png",
                            Title = "Atletiek"
                        },
                        new
                        {
                            Id = 4,
                            Category = "binnen sporten",
                            Description = "Badminton is een Olympische sport die wordt gespeeld met een racket en een shuttle. De shuttle wordt over een net heen en weer geslagen met de rackets. Afhankelijk van met hoeveel personen je op de baan staat speel je een enkelspel of een dubbelspel. Bij een enkelspel speel je één tegen één en bij een dubbelspel twee tegen twee.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/277168663_7600580646633713_135095285667829979_n-1024x545.jpeg",
                            Title = "Badminton"
                        },
                        new
                        {
                            Id = 5,
                            Category = "binnen sporten",
                            Description = "Basketbal is een van oorsprong Amerikaanse balsport waarbij je een bal moet veroveren en deze door de ring (de basket) van de tegenpartij moet gooien. Natuurlijk moet je proberen te voorkomen dat de tegenstander hetzelfde bij jou doet.\r\n\r\nTijdens de training op donderdagavond ligt de focus echt op het verbeteren van je balvaardigheid, techniek, regelkennis en tactiek en tijdens de training op de dinsdagavond worden er vriendschappelijke wedstrijden gespeeld (de teams worden ter plaatse gevormd).\r\n\r\nJe kunt het gehele jaar door bij beide trainingsmomenten aansluiten en je hoeft geen basketbal ervaring te hebben.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/DSC_8600-1024x684.jpg",
                            Title = "Basketbal"
                        },
                        new
                        {
                            Id = 6,
                            Category = "binnen sporten",
                            Description = "Tijdens de BBB-attack staat het trainen van jouw buik, benen en billen centraal. Door oefeningen uit te voeren die zich focussen op deze 3 gebieden komen deze binnen no-time weer in shape!",
                            Duration = 45,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/man-doing-sit-ups-2021-08-26-15-34-39-utc-scaled-e1653393049902-1024x538.jpg",
                            Title = "BBB-attack"
                        },
                        new
                        {
                            Id = 7,
                            Category = "buiten sporten",
                            Description = "Wie kent het spelletje met de 2 rackets en het kleine plastic balletje voor op het strand of op de camping niet? Inmiddels is dit spelletje geëvolueerd in een echte sport, genaamd beachtennis. Beachtennis is een snelgroeiende beachsport die zijn oorsprong vindt in Amerika en Brazilië. Het grote verschil met reguliere tennis is dat er bij beachtennis geen ingewikkelde lijnen zijn; met de buitenlijnen en een net ben je al klaar!",
                            Duration = 120,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/beach-tennis-player-at-the-net-2021-08-29-19-24-52-utc-1024x683.jpg",
                            Price = 12m,
                            Title = "Beachtennis"
                        },
                        new
                        {
                            Id = 8,
                            Category = "buiten sporten",
                            Description = "Beachvolleybal wordt gespeeld in zand en in tegenstelling tot normaal volleybal bestaat een team (officieel) maar uit 2 spelers. Twee andere grote verschillen zijn dat de spelers geen vaste posities in het veld hebben en dat de bal zwaarder en zachter is.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/a-beach-volleyball-net-on-the-beach-with-a-clear-a-2022-02-03-11-46-59-utc-1024x696.jpg",
                            Price = 10m,
                            Title = "Beachvolleybal"
                        },
                        new
                        {
                            Id = 9,
                            Category = "binnen sporten",
                            Description = "Ben jij wel toe aan wat ontspanning maar wil je tegelijkertijd wel je lichaam trainen? Volg dan de Body & Mind les van Robert. Tijdens deze les leer je gecontroleerd te ademhalen en verbeter je je flexibiliteit en statische kracht. Dankzij de meditatie oefeningen verbeter je ook nog eens je concentratie. Alle oefeningen worden uitgevoerd met rustgevende muziek op de achtergrond maar vergis je niet; dit is absoluut geen suffe les!",
                            Duration = 50,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/girl-in-black-sport-clothes-have-planking-exercise-2021-08-30-00-36-32-utc-1024x683.jpg",
                            Title = "Body and mind"
                        },
                        new
                        {
                            Id = 10,
                            Category = "binnen sporten",
                            Description = "Bodyshape is al jaren één van de populairste groepslessen van BRESS. Deze les start met pittige aerobics oefeningen gevolgd door een blok spierversterkende oefeningen. De ideale combinatie!\r\n\r\nDe aerobics oefeningen worden uitgevoerd op uptempo Dance muziek. Tijdens de spierversterkende oefeningen worden vooral de grote spiergroepen aangepakt waardoor de vetverbranding optimaal wordt. Onder andere oefeningen als lunges, squats, crunches, planken, leg lifts, hip thrusts en push-ups komen aan bod.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-23-om-16.59.44-1024x326.png",
                            Title = "Bodyshape"
                        },
                        new
                        {
                            Id = 11,
                            Category = "binnen sporten",
                            Description = "Boogschieten is een sport waarbij pijlen worden weggeschoten naar een doel met behulp van een boog. Hoewel vroeger de pijl en boog werd gebruikt als jacht- en oorlogswapen, is boogschieten tegenwoordig vooral een concentratiesport. Bij iedere te schieten pijl moet je het maximale halen uit je concentratie, schiethouding, ademhaling en techniek.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/powerful-female-archer-aiming-with-bow-and-arrow-2021-11-02-17-54-36-utc-1024x576.jpg",
                            Price = 50m,
                            Title = "Boogschieten"
                        },
                        new
                        {
                            Id = 12,
                            Category = "conditie en kracht",
                            Description = "Bootcamp is groepstraining die conditie- en krachtoefeningen combineert en buiten plaatsvindt. Tijdens veel oefeningen wordt er gebruik gemaakt van eigen lichaamsgewicht en obstakels die in de omgeving aanwezig zijn, denk bijvoorbeeld aan bankjes, stoepranden en hekken. Sommige oefeningen doe je in tweetallen of in kleine groepjes, zodat je elkaar kunt gebruiken om bepaalde oefeningen uit te voeren en elkaar aan te moedigen. Samen bereik je meer!",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-23-om-16.47.36-1024x959.png",
                            Price = 2.5m,
                            Title = "Bootcamp"
                        },
                        new
                        {
                            Id = 13,
                            Category = "conditie en kracht",
                            Description = "Sta jij ingeschreven voor een obstacle event en wil je hiervoor trainen? Of houd je gewoon van buiten sporten en vind je het tof om bootcamp te combineren met het klimmen over obstakels? Wat het ook is; de bootcamp & obstacle training heeft het allemaal! Deze training is een unieke combinatie van intensieve motivatie, stimulans en gezelligheid in groepsverband, dit alles in de buitenlucht. Tijdens een training ga je hardlopen en o.a. krachtoefeningen, circuit- en TRX-trainingen doen, gevolgd door één (of meerdere) rondje(s) over de obstacle baan.",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/fit-people-performing-crunches-exercise-2021-08-28-17-57-48-utc-scaled-e1653317042267-1024x540.jpg",
                            Price = 2.5m,
                            Title = "Bootcamp & Obstacle Training"
                        },
                        new
                        {
                            Id = 14,
                            Category = "conditie en kracht",
                            Description = "Boulderen is een spectaculaire vorm van klimmen en komt voort uit het beklimmen van rotsblokken. Anders dan bij klimmen heb je bij boulderen geen touw en klimgordels nodig. Dikke valmatten onder de routes zorgen voor veiligheid. De klimwanden in de boulderhal hebben een maximale hoogte van 4,5 meter en variëren van voorover neigend tot en met fors achterover hellend. Het is een sport voor vrijwel iedereen en kan zowel individueel als in groepsverband beoefend worden. Door de mix van de verschillende wanden en boulders kunnen zowel beginnende klimmers als gevorderden naast en met elkaar boulderen.",
                            Duration = 120,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/bouldering-2021-08-28-18-47-52-utc-scaled-e1650881591375-1024x530.jpg",
                            Price = 6.5m,
                            Title = "Boulderen"
                        },
                        new
                        {
                            Id = 15,
                            Category = "kracht",
                            Description = "Tijdens de high intensity training BoxFit krijg je te maken met een combinatie van bokstechnieken en oefeningen met eigen lichaamsgewicht, waarbij fun en samenwerking centraal staat.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-17.27.25-1022x1024.png",
                            Title = "BoxFit"
                        },
                        new
                        {
                            Id = 20,
                            Category = "groepsles",
                            Description = "Duiken is één van de snelst groeiende avontuurlijke sporten ter wereld en dat is niet zonder reden. Het ontspannen gevoel en het gevoel van gewichtloosheid (een gevoel dat verder alleen astronauten kunnen meemaken) maakt duiken tot een unieke sport. Duiken doe je altijd met minimaal 2 personen waardoor het ook nog eens een sociale sport is. Wist je trouwens dat het aardoppervlakte\r\nuit 70% water bestaat en dat er onder water meer verschillende soorten planten en dieren leven dan erboven? Er valt dus nog genoeg te ontdekken in de onderwaterwereld!",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/Schermafbeelding-2022-05-18-om-11.08.38-1024x327.png",
                            Title = "Duiken"
                        },
                        new
                        {
                            Id = 18,
                            Category = "kracht",
                            Description = "Onze fitness beschikt over de up-to-date cardio- en krachtapparatuur van Matrix Fitness en daarnaast ook over een free weight area waar je alle ruimte hebt om (grond)oefeningen te doen of te trainen met dumbbells, barbells en andere materialen.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/interior-of-fitness-hall-with-fitness-bicycles-2021-08-28-00-35-59-utc-1024x683.jpg",
                            Title = "Fitness"
                        },
                        new
                        {
                            Id = 16,
                            Category = "conditie en kracht",
                            Description = "Bij onze gymlessen maak je na een lange werkdag je hoofd weer even helemaal leeg. De nostalgie slaat zó hard in dat de smaak van Wicky spontaan weer te proeven is! Elke les bestaat uit een warming-up, een hoofdspel en een eindspel. De opgeleide meesters en juffen van ApenkooiGym doen er alles aan om jou zo hard mogelijk door de zaal te laten gieren. De ene keer is dat met Apenkooien, de andere keer met bestaande of zelfbedachte spellen als James Bond, het Grote Waterspektakel, Super Mario Kart of één van de vele varianten op trefbal. Al deze spellen zijn (her)uitgevonden voor volwassenen. Nooit kinderachtig, altijd met kinderlijk plezier. Door het trainen van je lachspieren heb je bijna niet in de gaten dat je met een aardige work-out bezig bent.",
                            Duration = 75,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-14.52.29-1024x854.png",
                            Price = 2.5m,
                            Title = "Gymmen"
                        },
                        new
                        {
                            Id = 17,
                            Category = "cardio",
                            Description = "Spinning is een high intensity groepsles waarbij je op een leuke manier je conditie in hoog tempo verbetert. Je doet dit op een vaststaande fiets, met extra weerstand. Hoeveel weerstand? Dit bepaal je helemaal zelf! Hierdoor is deze les geschikt voor iedereen. De instructeur geeft instructies terwijl de muziek het tempo ondersteunt.",
                            Duration = 60,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/Schermafbeelding-2022-03-30-om-14.40.03-1024x939.png",
                            Title = "Spinning"
                        },
                        new
                        {
                            Id = 19,
                            Category = "balsport",
                            Description = "Tennis is een balsport voor twee spelers (enkelspel) of paren (dubbelspel). De tennisbal moet met een racket over een net op de speelhelft van de tegenspeler(s) geslagen worden. Het doel is om het de tegenspelers(s) onmogelijk te maken de bal terug te slaan.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/tennis-racket-and-tennis-net-on-tennis-court-2021-09-03-12-45-52-utc-1024x683.jpg",
                            Title = "Tennis"
                        },
                        new
                        {
                            Id = 21,
                            Category = "dans",
                            Description = "Zouk betekent ‘feest’ in het Frans Creools en is een muziekgenre uit de Franse Antillen. De dans Zouk is net zo vrolijk als de muziek en kwam op in de jaren 60 op de Caraïbische eilanden. Ook in Brazilië is Zouk populair geworden, maar dan onder de naam Kizomba. De dans biedt veel ruimte voor variatie en creativiteit en door het toom-chic-chic (slow-quick-quick) tempo is deze heel elegant. De mannen leiden en bepalen de volgorde van de figuren. De vrouwen maken bewegingen met hun hoofd waardoor hun haar in de lucht zwiert.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/05/young-couple-dancing-latin-dance-bachata-merengue-2022-01-11-06-15-58-utc-scaled-e1652359701676-1024x546.jpg",
                            Price = 55m,
                            Title = "Zouk"
                        },
                        new
                        {
                            Id = 22,
                            Category = "atletiek",
                            Description = "Zwemmen is supergezond! Je verbrandt er razendsnel calorieën mee en het verbetert je conditie. Het fijne aan zwemmen is dat je je spieren en gewrichten gebruikt op een niet-belastende manier, hierdoor blijven deze soepeler.\r\nWanneer je een echte waterrat bent dan heb je geluk; Breda telt maar liefst 3 Optisport zwembaden waar je als BRESS-lid baantjes kunt trekken of recreatief kunt zwemmen.",
                            Duration = 90,
                            Image = "https://bress.nl/wp-content/uploads/2022/03/male-swimmer-swimming-laps-in-a-pool-2021-08-26-19-58-29-utc-scaled-e1648646593733-1024x388.jpg",
                            Price = 35m,
                            Title = "Zwemmen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
